export const API_ENDPOINTS = Object.freeze({
  health: '/health',
  status: '/status',
  signals: '/signals',
  scannerStatus: '/scanner/status',
  scannerLatest: '/scanner/latest',
  scannerRun: '/scanner/run',
  storageStatus: '/storage/status',
  dataStatus: '/data/status',
  dataSource: '/data/source',
  dataAudit: '/data/audit',
  previewOhlc: '/data/ohlc/preview',
  importOhlcToLocal: '/data/ohlc/import-blob',
  importOhlcToDatabase: '/data/ohlc/import-db',
  databaseStatus: '/db/status',
  initializeDatabase: '/db/init',
  collectorRun: '/collector/run',
  collectorProductionStatus: '/collector/status',
  collectorStart: '/collector/start',
  collectorStop: '/collector/stop',
  collectorLatest: '/collector/latest',
  collectorStatus: (jobId: string) => `/collector/status/${encodeURIComponent(jobId)}`,
  collectorHistory: (limit: number) => `/collector/history?limit=${limit}`,
});
