export interface Candidate {
  id: string;
  rank: number;
  symbol: string;
  company: string;
  sector: string;
  setup: string;
  side: 'LONG' | 'SHORT' | null;
  grade: 'A+' | 'A' | 'B+' | 'Reject' | 'REJECT';
  score: number;
  price: number;
  changePercent: number | null | undefined;
  relativeVolume: number;
  averageVolume: string;
  turnover: string;
  rsi: number;
  trend: 'BULLISH' | 'BEARISH' | 'NEUTRAL';
  emaAlignment: 'BULLISH' | 'BEARISH' | 'NEUTRAL';
  entryStatus: 'READY' | 'NEAR' | 'WATCH';
  entryLow: number | null;
  entryHigh: number | null;
  stopLoss: number | null;
  target1: number | null;
  target2: number | null;
  target3: number | null;
  riskReward: number | null;
  support: number | null;
  resistance: number | null;
  qualificationReasons: string[];
  missingConditions: string[];
  rejectionReasons: string[];
  updatedAt: string;
  dataMode: string;
}
